#!/usr/bin/env python
#coding:utf-8
# Author:  mozman
# Purpose: svg base element
# Created: 11.09.2010
# Copyright (C) 2010, Manfred Moitzi
# License: GPLv3

def check_attribs(elementname, attribs):
    """Checks if all attribute-names (keys of attribs) for elementname are valid."""
    valid_attribs = attributs[elementname]
    for key in attribs.iterkeys():
        if key not in valid_attribs:
            raise ValueError("Invalid attribute '%s' for element '%s'." % (key, elementname))
    return attribs

attributs = {
'a': ("class", "externalResourcesRequired", "style", "target", "transform",
      "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show",
      "xlink:title", "xlink:type", "xmlns:xlink"),
'altGlyph': ("class", "dx", "dy", "externalResourcesRequired", "format", "glyphRef",
             "rotate", "style", "x", "xlink:href", "y"),
'animAdditionAttrs': ("accumulate",),
'animAttributeAttrs': ("attributeType",),
'animElementAttrs': ("xlink:href",),
'animTimingAttrs': ("dur", "end", "fill", "max", "min", "repeatCount", "repeatDur",
                    "restart"),
'animValueAttrs': ("by", "from", "keySplines", "keyTimes", "to", "values"),
'animate': ("externalResourcesRequired",),
'animateColor': ("externalResourcesRequired",),
'animateMotion': ("by", "calcMode", "externalResourcesRequired", "from", "keyPoints",
                  "keySplines", "keyTimes", "origin", "path", "rotate", "to", "values"),
'animateTransform': ("externalResourcesRequired", "type"),
'animationEvents': ("onbegin", "onend", "onrepeat"),
'circle': ("class", "cx", "cy", "externalResourcesRequired", "r", "style", "transform"),
'clipPath': ("class", "clipPathUnits", "externalResourcesRequired", "style", "transform"),
'colo':("r-profile", "local", "name", "rendering-intent", "xlink:href"),
'component_transfer_function_attributes': ("amplitude", "exponent", "intercept",
                                           "offset", "slope", "tableValues", "type"),
'cursor': ("externalResourcesRequired", "x", "xlink:href", "y"),
'definition-src': ("xlink:href",),
'defs': ("class", "externalResourcesRequired", "style", "transform"),
'desc': ("class", "style"),
'documentEvents': ("onabort", "onerror", "onresize", "onscroll", "onunload", "onzoom"),
'ellipse': ("class", "cx", "cy", "externalResourcesRequired", "rx", "ry", "style", "transform"),
'feBlend': ("in2", "mode"),
'feColorMatrix': ("type", "values"),
'feComposite': ("in2", "k1", "k2", "k3", "k4", "operator"),
'feConvolveMatrix': ("bias", "divisor", "edgeMode", "kernelMatrix", "kernelUnitLength",
                     "order", "preserveAlpha", "targetX", "targetY"),
'feDiffuseLighting': ("class", "diffuseConstant", "kernelUnitLength", "surfaceScale"),
'feDisplacementMap': ("in2", "scale", "xChannelSelector", "yChannelSelector"),
'feDistantLight': ("azimuth", "elevation"),
'feFlood': ("class",),
'feGaussianBlur': ("stdDeviation",),
'feImage': ("class", "externalResourcesRequired", "style", "xlink:href"),
'feMergeNode': ("in",),
'feMorphology': ("operator", "radius"),
'feOffset': ("dx", "dy"),
'fePointLight': ("x", "y", "z"),
'feSpecularLighting': ("class", "kernelUnitLength", "specularConstant", "specularExponent",
                       "surfaceScale"),
'feSpotLight': ("limitingConeAngle", "pointsAtX", "pointsAtY", "pointsAtZ", "specularExponent",
                "x", "y", "z"),
'feTurbulence': ("baseFrequency", "numOctaves", "seed", "stitchTiles", "type"),
'filter': ("animate", "class", "externalResourcesRequired", "feColorMatrix",
           "feComposite", "feGaussianBlur", "feMorphology", "feTile", "filterRes",
           "filterUnits", "height", "primitiveUnits", "style", "width", "x", "xlink:href", "y"),
'font': ("class", "externalResourcesRequired", "horiz-adv-x", "horiz-origin-x",
         "horiz-origin-y", "style", "vert-adv-y", "vert-origin-x", "vert-origin-y"),
'font-face': ("accent-height", "alphabetic", "ascent", "bbox", "cap-height", "descent",
              "font-family", "font-size", "font-stretch", "font-style", "font-variant",
              "font-weight", "hanging", "ideographic", "mathematical", "overline-position",
              "overline-thickness", "panose-1", "slope", "stemh", "stemv", "strikethrough-position",
              "strikethrough-thickness", "underline-position", "underline-thickness", "unicode-range",
              "units-per-em", "v-alphabetic", "v-hanging", "v-ideographic", "v-mathematical",
              "widths", "x-height"),
'font-face-uri': ("xlink:href",),
'foreignObject': ("class", "externalResourcesRequired", "height", "style", "transform",
                  "width", "x", "y"),
'g': ("class", "externalResourcesRequired", "style", "transform"),
'glyph': ("arabic-form", "class", "d", "glyph-name", "horiz-adv-x", "lang", "orientation",
          "style", "unicode", "vert-adv-y", "vert-origin-x", "vert-origin-y"),
'glyphRef': ("class", "dx", "dy", "format", "glyphRef", "style", "x", "xlink:href", "y"),
'graphicsElementEvents': ("onactivate", "onclick", "onfocusin", "onfocusout", "onload",
                          "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup"),
'hkern': ("g1", "g2", "k", "u1", "u2"),
'image': ("class", "externalResourcesRequired", "height", "preserveAspectRatio",
          "style", "transform", "width", "x", "xlink:href", "y"),
'langSpaceAttrs': ("xml:space",),
'line': ("class", "externalResourcesRequired", "style", "transform", "x1", "x2",
         "y1", "y2"),
'linearGradient': ("class", "externalResourcesRequired", "gradientTransform", "gradientUnits",
                   "spreadMethod", "style", "x1", "x2", "xlink:href", "y1", "y2"),
'marker': ("class", "externalResourcesRequired", "markerHeight", "markerUnits",
           "markerWidth", "orient", "preserveAspectRatio", "refX", "refY", "style",
           "viewBox"),
'mask': ("class", "externalResourcesRequired", "height", "maskContentUnits", "maskUnits",
         "style", "width", "x", "y"),
'missing-glyph': ("class", "d", "horiz-adv-x", "style", "vert-adv-y", "vert-origin-x",
                  "vert-origin-y"),
'mpath': ("externalResourcesRequired", "xlink:href"),
'path': ("class", "d", "externalResourcesRequired", "pathLength", "style", "transform"),
'pattern': ("class", "externalResourcesRequired", "height", "patternContentUnits",
            "patternTransform", "patternUnits", "preserveAspectRatio", "style",
            "viewBox", "width", "x", "xlink:href", "y"),
'polygon': ("class", "externalResourcesRequired", "points", "style", "transform"),
'polyline': ("class", "externalResourcesRequired", "points", "style", "transform"),
'radialGradient': ("class", "cx", "cy", "externalResourcesRequired", "fx", "fy",
                   "gradientTransform", "gradientUnits", "r", "spreadMethod",
                   "style", "xlink:href"),
'rect': ("class", "externalResourcesRequired", "height", "rx", "ry", "style",
         "transform", "width", "x", "y"),
'script': ("externalResourcesRequired", "type", "xlink:href"),
'set': ("externalResourcesRequired", "to"),
'stdAttrs': ("xml:base",),
'stop': ("class", "offset", "style"),
'style': ("media", "title", "type", "xml:space"),
'svg': ("baseProfile", "class", "contentScriptType", "contentStyleType", "externalResourcesRequired",
        "height", "preserveAspectRatio", "style", "version", "viewBox", "width",
        "x", "xmlns", "y", "zoomAndPan"),
'switch': ("class", "externalResourcesRequired", "style", "transform"),
'symbol': ("class", "externalResourcesRequired", "preserveAspectRatio", "style",
           "viewBox"),
'testAttrs': ("requiredExtensions", "systemLanguage"),
'text': ("class", "dx", "dy", "externalResourcesRequired", "lengthAdjust", "rotate",
         "style", "textLength", "transform", "x", "y"),
'textPath': ("class", "externalResourcesRequired", "lengthAdjust", "method", "spacing",
             "startOffset", "style", "textLength", "xlink:href"),
'title': ("class", "style"),
'tref': ("class", "dx", "dy", "externalResourcesRequired", "lengthAdjust", "rotate",
         "style", "textLength", "x", "xlink:href", "y"),
'tspan': ("class", "dx", "dy", "externalResourcesRequired", "lengthAdjust", "rotate",
          "style", "textLength", "x", "y"),
'use': ("class", "externalResourcesRequired", "height", "style", "transform", "width",
        "x", "xlink:href", "y"),
'view': ("externalResourcesRequired", "preserveAspectRatio", "viewBox", "viewTarget",
         "zoomAndPan"),
'vkern': ("g1", "g2", "k", "u1", "u2"),
'xlinkRefAttrs': ("xlink:actuate", "xlink:arcrole", "xlink:role", "xlink:show",
                  "xlink:title", "xlink:type"),
'xlinkRefAttrsEmbed': ("xlink:actuate", "xlink:arcrole", "xlink:role", "xlink:show",
                       "xlink:title", "xlink:type")}