#!/usr/bin/env python
#coding:utf-8
# Author:  mozman
# Purpose: svg base element
# Created: 11.09.2010
# Copyright (C) 2010, Manfred Moitzi
# License: GPLv3

import re

def check_attribute_names(elementname, attribs):
    """Checks if all attribute-names (keys of attribs) for element 'elementname'
    are valid.

    Raises ValueError if not valid.
    """
    valid_attribs = attributs[elementname]
    for key in attribs.iterkeys():
        if key not in valid_attribs:
            raise ValueError("Invalid attribute '%s' for element '%s'." % (key, elementname))
    return attribs # pass-through function

def check_attribute_value(attributename, value):
    """Checks if value is valid for attribute 'attribute-name'.

    Raises ValueError if not valid.
    """
    if not isinstance(value, basestring):
        value = unicode(value)
    if not validate_attribute[attributename](value):
        raise ValueError("Value '%s' is not valid for atttribute '%s'." % (value, attributename))
    return value # pass-through function

def get_coordinate(value, profile='tiny'):
    """ Split value in (number, unit) if value has an unit or (number, None).

    Raises ValueError if not valid.
    """
    if isinstance(value, (int, float)):
        number, unit = float(value), None
    else:
        result = _coordinate_pattern.match(value.strip())
        if result:
            number, tmp, unit = result.groups()
            number = float(number)
        else:
            raise ValueError("'%s' has not a valid svg coordinate." % value)
    if profile == 'tiny': # check value range of tiny profile
        number = check_tiny(round(number, 4)) # round to four places for tiny profile
    return number, unit

def check_coordinate(value, profile='tiny'):
    """ Check if value is a valid coordinate, raises ValueError if not valid.

    Raises ValueError if not valid.
    """
    number, unit = get_coordinate(value, profile)
    return value

def check_tiny(number):
    """ Check if number is a valid 'tiny' coordinate, raises ValueError if not valid.

    Raises ValueError if not valid.
    """
    if not (-32767.9999 <= number <= 32767.9999):
        raise ValueError("'%.4f' out of range for baseProfile 'tiny'" % number)
    return number # pass-through function

attributs = {
    'a': ("class", "externalResourcesRequired", "style", "target", "transform",
          "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show",
          "xlink:title", "xlink:type", "xmlns:xlink"),
    'altGlyph': ("class", "dx", "dy", "externalResourcesRequired", "format", "glyphRef",
                 "rotate", "style", "x", "xlink:href", "y"),
    'animAdditionAttrs': ("accumulate",),
    'animAttributeAttrs': ("attributeType",),
    'animElementAttrs': ("xlink:href",),
    'animTimingAttrs': ("dur", "end", "fill", "max", "min", "repeatCount", "repeatDur",
                        "restart"),
    'animValueAttrs': ("by", "from", "keySplines", "keyTimes", "to", "values"),
    'animate': ("externalResourcesRequired",),
    'animateColor': ("externalResourcesRequired",),
    'animateMotion': ("by", "calcMode", "externalResourcesRequired", "from", "keyPoints",
                      "keySplines", "keyTimes", "origin", "path", "rotate", "to", "values"),
    'animateTransform': ("externalResourcesRequired", "type"),
    'animationEvents': ("onbegin", "onend", "onrepeat"),
    'circle': ("class", "cx", "cy", "externalResourcesRequired", "r", "style", "transform"),
    'clipPath': ("class", "clipPathUnits", "externalResourcesRequired", "style", "transform"),
    'colo':("r-profile", "local", "name", "rendering-intent", "xlink:href"),
    'component_transfer_function_attributes': ("amplitude", "exponent", "intercept",
                                               "offset", "slope", "tableValues", "type"),
    'cursor': ("externalResourcesRequired", "x", "xlink:href", "y"),
    'definition-src': ("xlink:href",),
    'defs': ("class", "externalResourcesRequired", "style", "transform"),
    'desc': ("class", "style"),
    'documentEvents': ("onabort", "onerror", "onresize", "onscroll", "onunload", "onzoom"),
    'ellipse': ("class", "cx", "cy", "externalResourcesRequired", "rx", "ry", "style", "transform"),
    'feBlend': ("in2", "mode"),
    'feColorMatrix': ("type", "values"),
    'feComposite': ("in2", "k1", "k2", "k3", "k4", "operator"),
    'feConvolveMatrix': ("bias", "divisor", "edgeMode", "kernelMatrix", "kernelUnitLength",
                         "order", "preserveAlpha", "targetX", "targetY"),
    'feDiffuseLighting': ("class", "diffuseConstant", "kernelUnitLength", "surfaceScale"),
    'feDisplacementMap': ("in2", "scale", "xChannelSelector", "yChannelSelector"),
    'feDistantLight': ("azimuth", "elevation"),
    'feFlood': ("class",),
    'feGaussianBlur': ("stdDeviation",),
    'feImage': ("class", "externalResourcesRequired", "style", "xlink:href"),
    'feMergeNode': ("in",),
    'feMorphology': ("operator", "radius"),
    'feOffset': ("dx", "dy"),
    'fePointLight': ("x", "y", "z"),
    'feSpecularLighting': ("class", "kernelUnitLength", "specularConstant", "specularExponent",
                           "surfaceScale"),
    'feSpotLight': ("limitingConeAngle", "pointsAtX", "pointsAtY", "pointsAtZ", "specularExponent",
                    "x", "y", "z"),
    'feTurbulence': ("baseFrequency", "numOctaves", "seed", "stitchTiles", "type"),
    'filter': ("animate", "class", "externalResourcesRequired", "feColorMatrix",
               "feComposite", "feGaussianBlur", "feMorphology", "feTile", "filterRes",
               "filterUnits", "height", "primitiveUnits", "style", "width", "x", "xlink:href", "y"),
    'font': ("class", "externalResourcesRequired", "horiz-adv-x", "horiz-origin-x",
             "horiz-origin-y", "style", "vert-adv-y", "vert-origin-x", "vert-origin-y"),
    'font-face': ("accent-height", "alphabetic", "ascent", "bbox", "cap-height", "descent",
                  "font-family", "font-size", "font-stretch", "font-style", "font-variant",
                  "font-weight", "hanging", "ideographic", "mathematical", "overline-position",
                  "overline-thickness", "panose-1", "slope", "stemh", "stemv", "strikethrough-position",
                  "strikethrough-thickness", "underline-position", "underline-thickness", "unicode-range",
                  "units-per-em", "v-alphabetic", "v-hanging", "v-ideographic", "v-mathematical",
                  "widths", "x-height"),
    'font-face-uri': ("xlink:href",),
    'foreignObject': ("class", "externalResourcesRequired", "height", "style", "transform",
                      "width", "x", "y"),
    'g': ("class", "externalResourcesRequired", "style", "transform"),
    'glyph': ("arabic-form", "class", "d", "glyph-name", "horiz-adv-x", "lang", "orientation",
              "style", "unicode", "vert-adv-y", "vert-origin-x", "vert-origin-y"),
    'glyphRef': ("class", "dx", "dy", "format", "glyphRef", "style", "x", "xlink:href", "y"),
    'graphicsElementEvents': ("onactivate", "onclick", "onfocusin", "onfocusout", "onload",
                              "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup"),
    'hkern': ("g1", "g2", "k", "u1", "u2"),
    'image': ("class", "externalResourcesRequired", "height", "preserveAspectRatio",
              "style", "transform", "width", "x", "xlink:href", "y"),
    'langSpaceAttrs': ("xml:space",),
    'line': ("class", "externalResourcesRequired", "style", "transform", "x1", "x2",
             "y1", "y2"),
    'linearGradient': ("class", "externalResourcesRequired", "gradientTransform", "gradientUnits",
                       "spreadMethod", "style", "x1", "x2", "xlink:href", "y1", "y2"),
    'marker': ("class", "externalResourcesRequired", "markerHeight", "markerUnits",
               "markerWidth", "orient", "preserveAspectRatio", "refX", "refY", "style",
               "viewBox"),
    'mask': ("class", "externalResourcesRequired", "height", "maskContentUnits", "maskUnits",
             "style", "width", "x", "y"),
    'missing-glyph': ("class", "d", "horiz-adv-x", "style", "vert-adv-y", "vert-origin-x",
                      "vert-origin-y"),
    'mpath': ("externalResourcesRequired", "xlink:href"),
    'path': ("class", "d", "externalResourcesRequired", "pathLength", "style", "transform"),
    'pattern': ("class", "externalResourcesRequired", "height", "patternContentUnits",
                "patternTransform", "patternUnits", "preserveAspectRatio", "style",
                "viewBox", "width", "x", "xlink:href", "y"),
    'polygon': ("class", "externalResourcesRequired", "points", "style", "transform"),
    'polyline': ("class", "externalResourcesRequired", "points", "style", "transform"),
    'radialGradient': ("class", "cx", "cy", "externalResourcesRequired", "fx", "fy",
                       "gradientTransform", "gradientUnits", "r", "spreadMethod",
                       "style", "xlink:href"),
    'rect': ("class", "externalResourcesRequired", "height", "rx", "ry", "style",
             "transform", "width", "x", "y"),
    'script': ("externalResourcesRequired", "type", "xlink:href"),
    'set': ("externalResourcesRequired", "to"),
    'stdAttrs': ("xml:base",),
    'stop': ("class", "offset", "style"),
    'style': ("media", "title", "type", "xml:space"),
    'svg': ("baseProfile", "class", "contentScriptType", "contentStyleType", "externalResourcesRequired",
            "height", "preserveAspectRatio", "style", "version", "viewBox", "width",
            "x", "xmlns", "y", "zoomAndPan"),
    'switch': ("class", "externalResourcesRequired", "style", "transform"),
    'symbol': ("class", "externalResourcesRequired", "preserveAspectRatio", "style",
               "viewBox"),
    'testAttrs': ("requiredExtensions", "systemLanguage"),
    'text': ("class", "dx", "dy", "externalResourcesRequired", "lengthAdjust", "rotate",
             "style", "textLength", "transform", "x", "y"),
    'textPath': ("class", "externalResourcesRequired", "lengthAdjust", "method", "spacing",
                 "startOffset", "style", "textLength", "xlink:href"),
    'title': ("class", "style"),
    'tref': ("class", "dx", "dy", "externalResourcesRequired", "lengthAdjust", "rotate",
             "style", "textLength", "x", "xlink:href", "y"),
    'tspan': ("class", "dx", "dy", "externalResourcesRequired", "lengthAdjust", "rotate",
              "style", "textLength", "x", "y"),
    'use': ("class", "externalResourcesRequired", "height", "style", "transform", "width",
            "x", "xlink:href", "y"),
    'view': ("externalResourcesRequired", "preserveAspectRatio", "viewBox", "viewTarget",
             "zoomAndPan"),
    'vkern': ("g1", "g2", "k", "u1", "u2"),
    'xlinkRefAttrs': ("xlink:actuate", "xlink:arcrole", "xlink:role", "xlink:show",
                      "xlink:title", "xlink:type"),
    'xlinkRefAttrsEmbed': ("xlink:actuate", "xlink:arcrole", "xlink:role", "xlink:show",
                           "xlink:title", "xlink:type")}



def _always_valid(value):
    return True

_coordinate_pattern = re.compile("(^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)(cm|em|ex|in|mm|pc|pt|px|%)?$") # coordinates with optional unit
def _valid_coordinate(value):
    return _coordinate_pattern.match(value) is not None


validate_attribute = {
    'accent-height' : _always_valid,
    'accumulate' : _always_valid,
    'alphabetic' : _always_valid,
    'amplitude' : _always_valid,
    'animate' : _always_valid,
    'arabic-form' : _always_valid,
    'ascent' : _always_valid,
    'attributeType' : _always_valid,
    'azimuth' : _always_valid,
    'baseFrequency' : _always_valid,
    'baseProfile' : _always_valid,
    'bbox' : _always_valid,
    'bias' : _always_valid,
    'by' : _always_valid,
    'calcMode' : _always_valid,
    'cap-height' : _always_valid,
    'class' : _always_valid,
    'clipPathUnits' : _always_valid,
    'contentScriptType' : _always_valid,
    'contentStyleType' : _always_valid,
    'cx' : _valid_coordinate,
    'cy' : _valid_coordinate,
    'd' : _always_valid,
    'descent' : _always_valid,
    'diffuseConstant' : _always_valid,
    'divisor' : _always_valid,
    'dur' : _always_valid,
    'dx' : _always_valid,
    'dy' : _always_valid,
    'edgeMode' : _always_valid,
    'elevation' : _always_valid,
    'end' : _always_valid,
    'exponent' : _always_valid,
    'externalResourcesRequired' : _always_valid,
    'feColorMatrix' : _always_valid,
    'feComposite' : _always_valid,
    'feGaussianBlur' : _always_valid,
    'feMorphology' : _always_valid,
    'feTile' : _always_valid,
    'fill' : _always_valid,
    'filterRes' : _always_valid,
    'filterUnits' : _always_valid,
    'font-family' : _always_valid,
    'font-size' : _always_valid,
    'font-stretch' : _always_valid,
    'font-style' : _always_valid,
    'font-variant' : _always_valid,
    'font-weight' : _always_valid,
    'format' : _always_valid,
    'from' : _always_valid,
    'fx' : _always_valid,
    'fy' : _always_valid,
    'g1' : _always_valid,
    'g2' : _always_valid,
    'glyph-name' : _always_valid,
    'glyphRef' : _always_valid,
    'gradientTransform' : _always_valid,
    'gradientUnits' : _always_valid,
    'hanging' : _always_valid,
    'height' : _always_valid,
    'horiz-adv-x' : _always_valid,
    'horiz-origin-x' : _always_valid,
    'horiz-origin-y' : _always_valid,
    'ideographic' : _always_valid,
    'in' : _always_valid,
    'in2' : _always_valid,
    'intercept' : _always_valid,
    'k' : _always_valid,
    'k1' : _always_valid,
    'k2' : _always_valid,
    'k3' : _always_valid,
    'k4' : _always_valid,
    'kernelMatrix' : _always_valid,
    'kernelUnitLength' : _always_valid,
    'keyPoints' : _always_valid,
    'keySplines' : _always_valid,
    'keyTimes' : _always_valid,
    'lang' : _always_valid,
    'lengthAdjust' : _always_valid,
    'limitingConeAngle' : _always_valid,
    'local' : _always_valid,
    'markerHeight' : _always_valid,
    'markerUnits' : _always_valid,
    'markerWidth' : _always_valid,
    'maskContentUnits' : _always_valid,
    'maskUnits' : _always_valid,
    'mathematical' : _always_valid,
    'max' : _always_valid,
    'media' : _always_valid,
    'method' : _always_valid,
    'min' : _always_valid,
    'mode' : _always_valid,
    'name' : _always_valid,
    'numOctaves' : _always_valid,
    'offset' : _always_valid,
    'onabort' : _always_valid,
    'onactivate' : _always_valid,
    'onbegin' : _always_valid,
    'onclick' : _always_valid,
    'onend' : _always_valid,
    'onerror' : _always_valid,
    'onfocusin' : _always_valid,
    'onfocusout' : _always_valid,
    'onload' : _always_valid,
    'onmousedown' : _always_valid,
    'onmousemove' : _always_valid,
    'onmouseout' : _always_valid,
    'onmouseover' : _always_valid,
    'onmouseup' : _always_valid,
    'onrepeat' : _always_valid,
    'onresize' : _always_valid,
    'onscroll' : _always_valid,
    'onunload' : _always_valid,
    'onzoom' : _always_valid,
    'operator' : _always_valid,
    'order' : _always_valid,
    'orient' : _always_valid,
    'orientation' : _always_valid,
    'origin' : _always_valid,
    'overline-position' : _always_valid,
    'overline-thickness' : _always_valid,
    'panose-1' : _always_valid,
    'path' : _always_valid,
    'pathLength' : _always_valid,
    'patternContentUnits' : _always_valid,
    'patternTransform' : _always_valid,
    'patternUnits' : _always_valid,
    'points' : _always_valid,
    'pointsAtX' : _always_valid,
    'pointsAtY' : _always_valid,
    'pointsAtZ' : _always_valid,
    'preserveAlpha' : _always_valid,
    'preserveAspectRatio' : _always_valid,
    'primitiveUnits' : _always_valid,
    'r' : _valid_coordinate,
    'r-profile' : _always_valid,
    'radius' : _always_valid,
    'refX' : _always_valid,
    'refY' : _always_valid,
    'rendering-intent' : _always_valid,
    'repeatCount' : _always_valid,
    'repeatDur' : _always_valid,
    'requiredExtensions' : _always_valid,
    'restart' : _always_valid,
    'rotate' : _always_valid,
    'rx' : _valid_coordinate,
    'ry' : _valid_coordinate,
    'scale' : _always_valid,
    'seed' : _always_valid,
    'slope' : _always_valid,
    'spacing' : _always_valid,
    'specularConstant' : _always_valid,
    'specularExponent' : _always_valid,
    'spreadMethod' : _always_valid,
    'startOffset' : _always_valid,
    'stdDeviation' : _always_valid,
    'stemh' : _always_valid,
    'stemv' : _always_valid,
    'stitchTiles' : _always_valid,
    'strikethrough-position' : _always_valid,
    'strikethrough-thickness' : _always_valid,
    'style' : _always_valid,
    'surfaceScale' : _always_valid,
    'systemLanguage' : _always_valid,
    'tableValues' : _always_valid,
    'target' : _always_valid,
    'targetX' : _always_valid,
    'targetY' : _always_valid,
    'textLength' : _always_valid,
    'title' : _always_valid,
    'to' : _always_valid,
    'transform' : _always_valid,
    'type' : _always_valid,
    'u1' : _always_valid,
    'u2' : _always_valid,
    'underline-position' : _always_valid,
    'underline-thickness' : _always_valid,
    'unicode' : _always_valid,
    'unicode-range' : _always_valid,
    'units-per-em' : _always_valid,
    'v-alphabetic' : _always_valid,
    'v-hanging' : _always_valid,
    'v-ideographic' : _always_valid,
    'v-mathematical' : _always_valid,
    'values' : _always_valid,
    'version' : _always_valid,
    'vert-adv-y' : _always_valid,
    'vert-origin-x' : _always_valid,
    'vert-origin-y' : _always_valid,
    'viewBox' : _always_valid,
    'viewTarget' : _always_valid,
    'width' : _always_valid,
    'widths' : _always_valid,
    'x' : _valid_coordinate,
    'x-height' : _always_valid,
    'x1' : _valid_coordinate,
    'x2' : _valid_coordinate,
    'xChannelSelector' : _always_valid,
    'xlink:actuate' : _always_valid,
    'xlink:arcrole' : _always_valid,
    'xlink:href' : _always_valid,
    'xlink:role' : _always_valid,
    'xlink:show' : _always_valid,
    'xlink:title' : _always_valid,
    'xlink:type' : _always_valid,
    'xml:base' : _always_valid,
    'xml:space' : _always_valid,
    'xmlns' : _always_valid,
    'xmlns:xlink' : _always_valid,
    'y' : _valid_coordinate,
    'y1' : _valid_coordinate,
    'y2' : _valid_coordinate,
    'yChannelSelector' : _always_valid,
    'z' : _always_valid,
    'zoomAndPan' : _always_valid,
}