#!/usr/bin/env python
#coding:utf-8
# generated by:  C:\dev\svgwrite\makedata\tinydata.py

from svgwrite.properties import SVGProperty

tiny12_svg_properties = { 
    'about': SVGProperty('about', anim=True, inherit=False,
    types=[u'list-of-strings'],
    strings=[]),

    'accent-height': SVGProperty('accent-height', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'accumulate': SVGProperty('accumulate', anim=False, inherit=False,
    types=[],
    strings=[u'none', u'sum']),

    'additive': SVGProperty('additive', anim=False, inherit=False,
    types=[],
    strings=[u'replace', u'sum']),

    'alphabetic': SVGProperty('alphabetic', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'arabic-form': SVGProperty('arabic-form', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'ascent': SVGProperty('ascent', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'attributeName': SVGProperty('attributeName', anim=False, inherit=False,
    types=[u'QName'],
    strings=[]),

    'attributeType': SVGProperty('attributeType', anim=False, inherit=False,
    types=[],
    strings=[u'XML', u'CSS', u'auto']),

    'audio-level': SVGProperty('audio-level', anim=True, inherit=False,
    types=[u'number'],
    strings=[u'inherit']),

    'bandwidth': SVGProperty('bandwidth', anim=False, inherit=False,
    types=[u'number'],
    strings=[u'auto']),

    'baseProfile': SVGProperty('baseProfile', anim=False, inherit=False,
    types=[],
    strings=[u'none', u'tiny', u'basic', u'full']),

    'bbox': SVGProperty('bbox', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'begin': SVGProperty('begin', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'buffered-rendering': SVGProperty('buffered-rendering', anim=True, inherit=False,
    types=[],
    strings=[u'auto', u'dynamic', u'static', u'inherit']),

    'by': SVGProperty('by', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'calcMode': SVGProperty('calcMode', anim=False, inherit=False,
    types=[],
    strings=[u'discrete', u'linear', u'paced', u'spline']),

    'cap-height': SVGProperty('cap-height', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'class': SVGProperty('class', anim=True, inherit=False,
    types=[u'XML-NMTOKENS'],
    strings=[]),

    'color': SVGProperty('color', anim=True, inherit=True,
    types=[u'color'],
    strings=[u'inherit']),

    'color-rendering': SVGProperty('color-rendering', anim=True, inherit=True,
    types=[],
    strings=[u'auto', u'optimizeSpeed', u'optimizeQuality', u'inherit']),

    'content': SVGProperty('content', anim=True, inherit=False,
    types=[u'string'],
    strings=[]),

    'contentScriptType': SVGProperty('contentScriptType', anim=False, inherit=False,
    types=[u'content-type'],
    strings=[]),

    'cx': SVGProperty('cx', anim=True, inherit=False,
    types=[u'coordinate'],
    strings=[]),

    'cy': SVGProperty('cy', anim=True, inherit=False,
    types=[u'coordinate'],
    strings=[]),

    'd': SVGProperty('d', anim=True, inherit=False,
    types=[u'path-data'],
    strings=[]),

    'datatype': SVGProperty('datatype', anim=True, inherit=False,
    types=[u'string'],
    strings=[]),

    'defaultAction': SVGProperty('defaultAction', anim=False, inherit=False,
    types=[],
    strings=[u'perform', u'cancel']),

    'descent': SVGProperty('descent', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'direction': SVGProperty('direction', anim=False, inherit=True,
    types=[],
    strings=[u'ltr', u'rtl', u'inherit']),

    'display': SVGProperty('display', anim=True, inherit=False,
    types=[],
    strings=[u'inline', u'block', u'list-item', u'run-in', u'compact', u'marker', u'table', u'inline-table', u'table-row-group', u'table-header-group', u'table-footer-group', u'table-row', u'table-column-group', u'table-column', u'table-cell', u'table-caption', u'none', u'inherit']),

    'display-align': SVGProperty('display-align', anim=True, inherit=True,
    types=[],
    strings=[u'auto', u'before', u'center', u'after', u'inherit']),

    'dur': SVGProperty('dur', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'editable': SVGProperty('editable', anim=True, inherit=False,
    types=[],
    strings=[u'none', u'simple']),

    'end': SVGProperty('end', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'ev:event': SVGProperty('ev:event', anim=False, inherit=False,
    types=[u'XML-NMTOKEN'],
    strings=[]),

    'event': SVGProperty('event', anim=False, inherit=False,
    types=[u'XML-NMTOKEN'],
    strings=[]),

    'externalResourcesRequired': SVGProperty('externalResourcesRequired', anim=False, inherit=False,
    types=[u'boolean'],
    strings=[]),

    'fill': SVGProperty('fill', anim=True, inherit=True,
    types=[u'paint'],
    strings=[u'inherit']),

    'fill-opacity': SVGProperty('fill-opacity', anim=True, inherit=True,
    types=[u'number'],
    strings=[u'inherit']),

    'fill-rule': SVGProperty('fill-rule', anim=True, inherit=True,
    types=[],
    strings=[u'nonzero', u'evenodd', u'inherit']),

    'focusHighlight': SVGProperty('focusHighlight', anim=True, inherit=False,
    types=[],
    strings=[u'auto', u'none']),

    'focusable': SVGProperty('focusable', anim=True, inherit=False,
    types=[u'boolean'],
    strings=[u'auto']),

    'font-family': SVGProperty('font-family', anim=True, inherit=True,
    types=[u'font-family-value'],
    strings=[u'inherit']),

    'font-size': SVGProperty('font-size', anim=True, inherit=True,
    types=[u'font-size-value'],
    strings=[u'inherit']),

    'font-stretch': SVGProperty('font-stretch', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'font-style': SVGProperty('font-style', anim=True, inherit=True,
    types=[],
    strings=[u'normal', u'italic', u'oblique', u'inherit']),

    'font-variant': SVGProperty('font-variant', anim=True, inherit=True,
    types=[],
    strings=[u'normal', u'small-caps', u'inherit']),

    'font-weight': SVGProperty('font-weight', anim=True, inherit=True,
    types=[],
    strings=[u'normal', u'bold', u'bolder', u'lighter', u'100', u'200', u'300', u'400', u'500', u'600', u'700', u'800', u'900', u'inherit']),

    'from': SVGProperty('from', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'g1': SVGProperty('g1', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'g2': SVGProperty('g2', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'glyph-name': SVGProperty('glyph-name', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'gradientUnits': SVGProperty('gradientUnits', anim=True, inherit=False,
    types=[],
    strings=[u'userSpaceOnUse', u'objectBoundingBox']),

    'handler': SVGProperty('handler', anim=False, inherit=False,
    types=[u'IRI'],
    strings=[]),

    'hanging': SVGProperty('hanging', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'height': SVGProperty('height', anim=True, inherit=False,
    types=[u'length'],
    strings=[u'auto']),

    'horiz-adv-x': SVGProperty('horiz-adv-x', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'horiz-origin-x': SVGProperty('horiz-origin-x', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'id': SVGProperty('id', anim=False, inherit=False,
    types=[u'ID', u'NCName'],
    strings=[]),

    'ideographic': SVGProperty('ideographic', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'image-rendering': SVGProperty('image-rendering', anim=True, inherit=True,
    types=[],
    strings=[u'auto', u'optimizeSpeed', u'optimizeQuality', u'inherit']),

    'initialVisibility': SVGProperty('initialVisibility', anim=False, inherit=False,
    types=[],
    strings=[u'whenStarted', u'always']),

    'k': SVGProperty('k', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'keyPoints': SVGProperty('keyPoints', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'keySplines': SVGProperty('keySplines', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'keyTimes': SVGProperty('keyTimes', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'lang': SVGProperty('lang', anim=False, inherit=False,
    types=[u'list-of-language-ids'],
    strings=[]),

    'line-increment': SVGProperty('line-increment', anim=True, inherit=True,
    types=[u'number'],
    strings=[u'auto', u'inherit']),

    'mathematical': SVGProperty('mathematical', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'max': SVGProperty('max', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'mediaCharacterEncoding': SVGProperty('mediaCharacterEncoding', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'mediaContentEncodings': SVGProperty('mediaContentEncodings', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'mediaSize': SVGProperty('mediaSize', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'mediaTime': SVGProperty('mediaTime', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'min': SVGProperty('min', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'nav-down': SVGProperty('nav-down', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-down-left': SVGProperty('nav-down-left', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-down-right': SVGProperty('nav-down-right', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-left': SVGProperty('nav-left', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-next': SVGProperty('nav-next', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-prev': SVGProperty('nav-prev', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-right': SVGProperty('nav-right', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-up': SVGProperty('nav-up', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-up-left': SVGProperty('nav-up-left', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'nav-up-right': SVGProperty('nav-up-right', anim=True, inherit=False,
    types=[u'focus'],
    strings=[]),

    'observer': SVGProperty('observer', anim=False, inherit=False,
    types=[u'IDREF'],
    strings=[]),

    'offset': SVGProperty('offset', anim=True, inherit=False,
    types=[u'number'],
    strings=[]),

    'opacity': SVGProperty('opacity', anim=True, inherit=False,
    types=[u'number'],
    strings=[u'inherit']),

    'origin': SVGProperty('origin', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'overlay': SVGProperty('overlay', anim=False, inherit=False,
    types=[],
    strings=[u'none', u'top']),

    'overline-position': SVGProperty('overline-position', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'overline-thickness': SVGProperty('overline-thickness', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'panose-1': SVGProperty('panose-1', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'path': SVGProperty('path', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'pathLength': SVGProperty('pathLength', anim=True, inherit=False,
    types=[u'number'],
    strings=[]),

    'phase': SVGProperty('phase', anim=False, inherit=False,
    types=[],
    strings=[u'default', u'capture']),

    'playbackOrder': SVGProperty('playbackOrder', anim=False, inherit=False,
    types=[],
    strings=[u'all', u'forwardOnly']),

    'pointer-events': SVGProperty('pointer-events', anim=True, inherit=True,
    types=[],
    strings=[u'visiblePainted', u'visibleFill', u'visibleStroke', u'visible', u'painted', u'fill', u'stroke', u'all', u'none', u'inherit']),

    'points': SVGProperty('points', anim=True, inherit=False,
    types=[u'points-data'],
    strings=[]),

    'preserveAspectRatio': SVGProperty('preserveAspectRatio', anim=True, inherit=False,
    types=[u'text'],
    strings=[]),

    'propagate': SVGProperty('propagate', anim=False, inherit=False,
    types=[],
    strings=[u'continue', u'stop']),

    'property': SVGProperty('property', anim=True, inherit=False,
    types=[u'list-of-strings'],
    strings=[]),

    'r': SVGProperty('r', anim=True, inherit=False,
    types=[u'length'],
    strings=[]),

    'rel': SVGProperty('rel', anim=True, inherit=False,
    types=[u'list-of-strings'],
    strings=[]),

    'repeatCount': SVGProperty('repeatCount', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'repeatDur': SVGProperty('repeatDur', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'requiredExtensions': SVGProperty('requiredExtensions', anim=False, inherit=False,
    types=[u'list-of-IRIs'],
    strings=[]),

    'requiredFeatures': SVGProperty('requiredFeatures', anim=False, inherit=False,
    types=[u'list-of-IRIs'],
    strings=[]),

    'requiredFonts': SVGProperty('requiredFonts', anim=False, inherit=False,
    types=[u'list-of-family-names'],
    strings=[]),

    'requiredFormats': SVGProperty('requiredFormats', anim=False, inherit=False,
    types=[u'list-of-content-types'],
    strings=[]),

    'resource': SVGProperty('resource', anim=True, inherit=False,
    types=[u'string'],
    strings=[]),

    'restart': SVGProperty('restart', anim=False, inherit=False,
    types=[],
    strings=[u'always', u'never', u'whenNotActive']),

    'rev': SVGProperty('rev', anim=True, inherit=False,
    types=[u'list-of-strings'],
    strings=[]),

    'role': SVGProperty('role', anim=True, inherit=False,
    types=[u'list-of-strings'],
    strings=[]),

    'rotate': SVGProperty('rotate', anim=True, inherit=False,
    types=[u'list-of-numbers'],
    strings=[]),

    'rx': SVGProperty('rx', anim=True, inherit=False,
    types=[u'length'],
    strings=[]),

    'ry': SVGProperty('ry', anim=True, inherit=False,
    types=[u'length'],
    strings=[]),

    'shape-rendering': SVGProperty('shape-rendering', anim=True, inherit=True,
    types=[],
    strings=[u'auto', u'optimizeSpeed', u'crispEdges', u'geometricPrecision', u'inherit']),

    'slope': SVGProperty('slope', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'snapshotTime': SVGProperty('snapshotTime', anim=False, inherit=False,
    types=[u'Clock-value'],
    strings=[u'none']),

    'solid-color': SVGProperty('solid-color', anim=True, inherit=False,
    types=[u'color'],
    strings=[u'inherit']),

    'solid-opacity': SVGProperty('solid-opacity', anim=True, inherit=False,
    types=[u'number'],
    strings=[u'inherit']),

    'stemh': SVGProperty('stemh', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'stemv': SVGProperty('stemv', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'stop-color': SVGProperty('stop-color', anim=True, inherit=False,
    types=[u'color'],
    strings=[u'inherit']),

    'stop-opacity': SVGProperty('stop-opacity', anim=True, inherit=False,
    types=[u'number'],
    strings=[u'inherit']),

    'strikethrough-position': SVGProperty('strikethrough-position', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'strikethrough-thickness': SVGProperty('strikethrough-thickness', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'stroke': SVGProperty('stroke', anim=True, inherit=True,
    types=[u'paint'],
    strings=[u'inherit']),

    'stroke-dasharray': SVGProperty('stroke-dasharray', anim=True, inherit=True,
    types=[u'list-of-lengths'],
    strings=[u'none', u'inherit']),

    'stroke-dashoffset': SVGProperty('stroke-dashoffset', anim=True, inherit=True,
    types=[u'length'],
    strings=[u'inherit']),

    'stroke-linecap': SVGProperty('stroke-linecap', anim=True, inherit=True,
    types=[],
    strings=[u'butt', u'round', u'square', u'inherit']),

    'stroke-linejoin': SVGProperty('stroke-linejoin', anim=True, inherit=True,
    types=[],
    strings=[u'miter', u'round', u'bevel', u'inherit']),

    'stroke-miterlimit': SVGProperty('stroke-miterlimit', anim=True, inherit=True,
    types=[u'number'],
    strings=[u'inherit']),

    'stroke-opacity': SVGProperty('stroke-opacity', anim=True, inherit=True,
    types=[u'number'],
    strings=[u'inherit']),

    'stroke-width': SVGProperty('stroke-width', anim=True, inherit=True,
    types=[u'length'],
    strings=[u'inherit']),

    'syncBehavior': SVGProperty('syncBehavior', anim=False, inherit=False,
    types=[],
    strings=[u'canSlip', u'locked', u'independent', u'default']),

    'syncBehaviorDefault': SVGProperty('syncBehaviorDefault', anim=False, inherit=False,
    types=[],
    strings=[u'canSlip', u'locked', u'independent', u'inherit']),

    'syncMaster': SVGProperty('syncMaster', anim=False, inherit=False,
    types=[u'boolean'],
    strings=[]),

    'syncTolerance': SVGProperty('syncTolerance', anim=False, inherit=False,
    types=[u'Clock-value'],
    strings=[u'default']),

    'syncToleranceDefault': SVGProperty('syncToleranceDefault', anim=False, inherit=False,
    types=[u'Clock-value'],
    strings=[u'inherit']),

    'systemLanguage': SVGProperty('systemLanguage', anim=False, inherit=False,
    types=[u'list-of-language-ids'],
    strings=[]),

    'target': SVGProperty('target', anim=False, inherit=False,
    types=[u'IDREF'],
    strings=[]),

    'text-align': SVGProperty('text-align', anim=True, inherit=True,
    types=[],
    strings=[u'start', u'center', u'end', u'inherit']),

    'text-anchor': SVGProperty('text-anchor', anim=True, inherit=True,
    types=[],
    strings=[u'start', u'middle', u'end', u'inherit']),

    'text-rendering': SVGProperty('text-rendering', anim=True, inherit=True,
    types=[],
    strings=[u'auto', u'optimizeSpeed', u'optimizeLegibility', u'geometricPrecision', u'inherit']),

    'timelineBegin': SVGProperty('timelineBegin', anim=False, inherit=False,
    types=[],
    strings=[u'onLoad', u'onStart']),

    'to': SVGProperty('to', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'transform': SVGProperty('transform', anim=True, inherit=False,
    types=[u'transform'],
    strings=[u'none']),

    'transformBehavior': SVGProperty('transformBehavior', anim=False, inherit=False,
    types=[],
    strings=[u'geometric', u'pinned', u'pinned90', u'pinned180', u'pinned270']),

    'type': SVGProperty('type', anim=False, inherit=False,
    types=[],
    strings=[u'translate', u'scale', u'rotate', u'skewX', u'skewY']),

    'typeof': SVGProperty('typeof', anim=True, inherit=False,
    types=[u'list-of-strings'],
    strings=[]),

    'u1': SVGProperty('u1', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'u2': SVGProperty('u2', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'underline-position': SVGProperty('underline-position', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'underline-thickness': SVGProperty('underline-thickness', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'unicode': SVGProperty('unicode', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'unicode-bidi': SVGProperty('unicode-bidi', anim=False, inherit=False,
    types=[],
    strings=[u'normal', u'embed', u'bidi-override', u'inherit']),

    'unicode-range': SVGProperty('unicode-range', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'units-per-em': SVGProperty('units-per-em', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'values': SVGProperty('values', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'vector-effect': SVGProperty('vector-effect', anim=True, inherit=False,
    types=[],
    strings=[u'none', u'non-scaling-stroke', u'inherit']),

    'version': SVGProperty('version', anim=False, inherit=False,
    types=[],
    strings=[u'1.0', u'1.1', u'1.2']),

    'viewBox': SVGProperty('viewBox', anim=True, inherit=False,
    types=[u'text'],
    strings=[]),

    'viewport-fill': SVGProperty('viewport-fill', anim=True, inherit=False,
    types=[u'color'],
    strings=[u'none', u'inherit']),

    'viewport-fill-opacity': SVGProperty('viewport-fill-opacity', anim=True, inherit=False,
    types=[u'number'],
    strings=[u'inherit']),

    'visibility': SVGProperty('visibility', anim=True, inherit=True,
    types=[],
    strings=[u'visible', u'hidden', u'inherit']),

    'width': SVGProperty('width', anim=True, inherit=False,
    types=[u'length'],
    strings=[u'auto']),

    'widths': SVGProperty('widths', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'x': SVGProperty('x', anim=True, inherit=False,
    types=[u'list-of-coordinates'],
    strings=[]),

    'x-height': SVGProperty('x-height', anim=False, inherit=False,
    types=[u'number'],
    strings=[]),

    'x1': SVGProperty('x1', anim=True, inherit=False,
    types=[u'coordinate'],
    strings=[]),

    'x2': SVGProperty('x2', anim=True, inherit=False,
    types=[u'coordinate'],
    strings=[]),

    'xlink:actuate': SVGProperty('xlink:actuate', anim=False, inherit=False,
    types=[],
    strings=[u'onRequest']),

    'xlink:arcrole': SVGProperty('xlink:arcrole', anim=False, inherit=False,
    types=[u'IRI'],
    strings=[]),

    'xlink:href': SVGProperty('xlink:href', anim=True, inherit=False,
    types=[u'IRI'],
    strings=[]),

    'xlink:role': SVGProperty('xlink:role', anim=False, inherit=False,
    types=[u'IRI'],
    strings=[]),

    'xlink:show': SVGProperty('xlink:show', anim=False, inherit=False,
    types=[],
    strings=[u'new', u'replace']),

    'xlink:title': SVGProperty('xlink:title', anim=False, inherit=False,
    types=[u'text'],
    strings=[]),

    'xlink:type': SVGProperty('xlink:type', anim=True, inherit=False,
    types=[],
    strings=[u'simple']),

    'xml:base': SVGProperty('xml:base', anim=False, inherit=False,
    types=[u'IRI'],
    strings=[]),

    'xml:id': SVGProperty('xml:id', anim=False, inherit=False,
    types=[u'NCName'],
    strings=[]),

    'xml:lang': SVGProperty('xml:lang', anim=False, inherit=False,
    types=[u'language-id'],
    strings=[]),

    'xml:space': SVGProperty('xml:space', anim=False, inherit=False,
    types=[],
    strings=[u'preserve']),

    'y': SVGProperty('y', anim=True, inherit=False,
    types=[u'list-of-coordinates'],
    strings=[]),

    'y1': SVGProperty('y1', anim=True, inherit=False,
    types=[u'coordinate'],
    strings=[]),

    'y2': SVGProperty('y2', anim=True, inherit=False,
    types=[u'coordinate'],
    strings=[]),

    'zoomAndPan': SVGProperty('zoomAndPan', anim=False, inherit=False,
    types=[],
    strings=[u'disable', u'magnify']),

}
