#coding:utf-8
# generated by:  C:\dev\svgwrite\makedata\maketinydata.py

from svgwrite.types import SVGElement
from tiny12data import property_names, media_group_names

tiny12_elements = { 
SVGElement('a', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'target', u'transform', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=['likeparent']),

SVGElement('animate', attributes=[u'about', u'accumulate', u'additive', u'attributeName', u'attributeType', u'begin', u'by', u'calcMode', u'class', u'content', u'datatype', u'dur', u'end', u'fill', u'from', u'id', u'keySplines', u'keyTimes', u'max', u'min', u'property', u'rel', u'repeatCount', u'repeatDur', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'restart', u'rev', u'role', u'systemLanguage', u'to', u'typeof', u'values', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'handler', u'metadata', u'switch', u'title']),

SVGElement('animateColor', attributes=[u'about', u'accumulate', u'additive', u'attributeName', u'attributeType', u'begin', u'by', u'calcMode', u'class', u'content', u'datatype', u'dur', u'end', u'fill', u'from', u'id', u'keySplines', u'keyTimes', u'max', u'min', u'property', u'rel', u'repeatCount', u'repeatDur', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'restart', u'rev', u'role', u'systemLanguage', u'to', u'typeof', u'values', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'handler', u'metadata', u'switch', u'title']),

SVGElement('animateMotion', attributes=[u'about', u'accumulate', u'additive', u'begin', u'by', u'calcMode', u'class', u'content', u'datatype', u'dur', u'end', u'fill', u'from', u'id', u'keyPoints', u'keySplines', u'keyTimes', u'max', u'min', u'origin', u'path', u'property', u'rel', u'repeatCount', u'repeatDur', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'restart', u'rev', u'role', u'rotate', u'systemLanguage', u'to', u'typeof', u'values', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'handler', u'metadata', u'mpath', u'switch', u'title']),

SVGElement('animateTransform', attributes=[u'about', u'accumulate', u'additive', u'attributeName', u'attributeType', u'begin', u'by', u'calcMode', u'class', u'content', u'datatype', u'dur', u'end', u'fill', u'from', u'id', u'keySplines', u'keyTimes', u'max', u'min', u'property', u'rel', u'repeatCount', u'repeatDur', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'restart', u'rev', u'role', u'systemLanguage', u'to', u'type', u'typeof', u'values', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'handler', u'metadata', u'switch', u'title']),

SVGElement('animation', attributes=[u'about', u'begin', u'class', u'content', u'datatype', u'dur', u'end', u'externalResourcesRequired', u'fill', u'focusHighlight', u'focusable', u'height', u'id', u'initialVisibility', u'max', u'min', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'preserveAspectRatio', u'property', u'rel', u'repeatCount', u'repeatDur', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'restart', u'rev', u'role', u'syncBehavior', u'syncMaster', u'syncTolerance', u'systemLanguage', u'transform', u'typeof', u'width', u'x', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y'],
    properties=media_group_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('audio', attributes=[u'about', u'begin', u'class', u'content', u'datatype', u'dur', u'end', u'externalResourcesRequired', u'fill', u'id', u'max', u'min', u'property', u'rel', u'repeatCount', u'repeatDur', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'restart', u'rev', u'role', u'syncBehavior', u'syncMaster', u'syncTolerance', u'systemLanguage', u'type', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=media_group_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('circle', attributes=[u'about', u'class', u'content', u'cx', u'cy', u'datatype', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'r', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('defs', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'a', u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'animation', u'audio', u'circle', u'defs', u'desc', u'discard', u'ellipse', u'font', u'font-face', u'foreignObject', u'g', u'handler', u'image', u'line', u'linearGradient', u'listener', u'metadata', u'path', u'polygon', u'polyline', u'prefetch', u'radialGradient', u'rect', u'script', u'set', u'solidColor', u'switch', u'text', u'textArea', u'title', u'use', u'video']),

SVGElement('desc', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=media_group_names,
    children=[]),

SVGElement('discard', attributes=[u'about', u'begin', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'handler', u'metadata', u'switch', u'title']),

SVGElement('ellipse', attributes=[u'about', u'class', u'content', u'cx', u'cy', u'datatype', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'rx', u'ry', u'systemLanguage', u'transform', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('font', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'horiz-adv-x', u'horiz-origin-x', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'font-face', u'glyph', u'hkern', u'metadata', u'missing-glyph', u'switch', u'title']),

SVGElement('font-face', attributes=[u'about', u'accent-height', u'alphabetic', u'ascent', u'bbox', u'cap-height', u'class', u'content', u'datatype', u'descent', u'externalResourcesRequired', u'font-family', u'font-stretch', u'font-style', u'font-variant', u'font-weight', u'hanging', u'id', u'ideographic', u'mathematical', u'overline-position', u'overline-thickness', u'panose-1', u'property', u'rel', u'resource', u'rev', u'role', u'slope', u'stemh', u'stemv', u'strikethrough-position', u'strikethrough-thickness', u'typeof', u'underline-position', u'underline-thickness', u'unicode-range', u'units-per-em', u'widths', u'x-height', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'font-face-src', u'metadata', u'switch', u'title']),

SVGElement('font-face-src', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'font-face-uri', u'metadata', u'switch', u'title']),

SVGElement('font-face-uri', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'metadata', u'switch', u'title']),

SVGElement('foreignObject', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'focusHighlight', u'focusable', u'height', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'width', u'x', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y'],
    properties=property_names,
    children=[u'desc', u'metadata', u'svg', u'switch', u'title']),

SVGElement('g', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'a', u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'animation', u'audio', u'circle', u'defs', u'desc', u'discard', u'ellipse', u'font', u'font-face', u'foreignObject', u'g', u'handler', u'image', u'line', u'linearGradient', u'listener', u'metadata', u'path', u'polygon', u'polyline', u'prefetch', u'radialGradient', u'rect', u'script', u'set', u'solidColor', u'switch', u'text', u'textArea', u'title', u'use', u'video']),

SVGElement('glyph', attributes=[u'about', u'arabic-form', u'class', u'content', u'd', u'datatype', u'glyph-name', u'horiz-adv-x', u'id', u'lang', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'unicode', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'metadata', u'switch', u'title']),

SVGElement('handler', attributes=[u'about', u'class', u'content', u'datatype', u'ev:event', u'externalResourcesRequired', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'type', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'metadata', u'switch', u'title']),

SVGElement('hkern', attributes=[u'about', u'class', u'content', u'datatype', u'g1', u'g2', u'id', u'k', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'u1', u'u2', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'metadata', u'switch', u'title']),

SVGElement('image', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'focusHighlight', u'focusable', u'height', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'opacity', u'preserveAspectRatio', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'type', u'typeof', u'width', u'x', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y'],
    properties=media_group_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('line', attributes=[u'about', u'class', u'content', u'datatype', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'x1', u'x2', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y1', u'y2'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('linearGradient', attributes=[u'about', u'class', u'content', u'datatype', u'gradientUnits', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'x1', u'x2', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y1', u'y2'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'metadata', u'set', u'stop', u'switch', u'title']),

SVGElement('listener', attributes=[u'about', u'class', u'content', u'datatype', u'defaultAction', u'event', u'handler', u'id', u'observer', u'phase', u'propagate', u'property', u'rel', u'resource', u'rev', u'role', u'target', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=None),

SVGElement('metadata', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=media_group_names,
    children=[]),

SVGElement('missing-glyph', attributes=[u'about', u'class', u'content', u'd', u'datatype', u'horiz-adv-x', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'metadata', u'switch', u'title']),

SVGElement('mpath', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'metadata', u'switch', u'title']),

SVGElement('path', attributes=[u'about', u'class', u'content', u'd', u'datatype', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'pathLength', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('polygon', attributes=[u'about', u'class', u'content', u'datatype', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'points', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('polyline', attributes=[u'about', u'class', u'content', u'datatype', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'points', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('prefetch', attributes=[u'about', u'bandwidth', u'class', u'content', u'datatype', u'id', u'mediaCharacterEncoding', u'mediaContentEncodings', u'mediaSize', u'mediaTime', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'metadata', u'switch', u'title']),

SVGElement('radialGradient', attributes=[u'about', u'class', u'content', u'cx', u'cy', u'datatype', u'gradientUnits', u'id', u'property', u'r', u'rel', u'resource', u'rev', u'role', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'metadata', u'set', u'stop', u'switch', u'title']),

SVGElement('rect', attributes=[u'about', u'class', u'content', u'datatype', u'focusHighlight', u'focusable', u'height', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'rx', u'ry', u'systemLanguage', u'transform', u'typeof', u'width', u'x', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('script', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'type', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'metadata', u'switch', u'title']),

SVGElement('set', attributes=[u'about', u'attributeName', u'attributeType', u'begin', u'class', u'content', u'datatype', u'dur', u'end', u'fill', u'id', u'max', u'min', u'property', u'rel', u'repeatCount', u'repeatDur', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'restart', u'rev', u'role', u'systemLanguage', u'to', u'typeof', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=[u'desc', u'handler', u'metadata', u'switch', u'title']),

SVGElement('solidColor', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('stop', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'offset', u'property', u'rel', u'resource', u'rev', u'role', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'metadata', u'set', u'switch', u'title']),

SVGElement('svg', attributes=[u'about', u'baseProfile', u'class', u'content', u'contentScriptType', u'datatype', u'externalResourcesRequired', u'focusHighlight', u'focusable', u'height', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'playbackOrder', u'preserveAspectRatio', u'property', u'rel', u'resource', u'rev', u'role', u'snapshotTime', u'syncBehaviorDefault', u'syncToleranceDefault', u'timelineBegin', u'typeof', u'version', u'viewBox', u'width', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'zoomAndPan'],
    properties=property_names,
    children=[u'a', u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'animation', u'audio', u'circle', u'defs', u'desc', u'discard', u'ellipse', u'font', u'font-face', u'foreignObject', u'g', u'handler', u'image', u'line', u'linearGradient', u'listener', u'metadata', u'path', u'polygon', u'polyline', u'prefetch', u'radialGradient', u'rect', u'script', u'set', u'solidColor', u'switch', u'text', u'textArea', u'title', u'use', u'video']),

SVGElement('switch', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=['likeparent']),

SVGElement('tbreak', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=None,
    children=None),

SVGElement('text', attributes=[u'about', u'class', u'content', u'datatype', u'editable', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'rotate', u'systemLanguage', u'transform', u'typeof', u'x', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y'],
    properties=property_names,
    children=[u'a', u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title', u'tspan']),

SVGElement('textArea', attributes=[u'about', u'class', u'content', u'datatype', u'editable', u'focusHighlight', u'focusable', u'height', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'width', u'x', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y'],
    properties=property_names,
    children=[u'a', u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'tbreak', u'title', u'tspan']),

SVGElement('title', attributes=[u'about', u'class', u'content', u'datatype', u'id', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=media_group_names,
    children=[]),

SVGElement('tspan', attributes=[u'about', u'class', u'content', u'datatype', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'typeof', u'xml:base', u'xml:id', u'xml:lang', u'xml:space'],
    properties=property_names,
    children=['likeparent']),

SVGElement('use', attributes=[u'about', u'class', u'content', u'datatype', u'externalResourcesRequired', u'focusHighlight', u'focusable', u'id', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'property', u'rel', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'rev', u'role', u'systemLanguage', u'transform', u'typeof', u'x', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y'],
    properties=property_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

SVGElement('video', attributes=[u'about', u'begin', u'class', u'content', u'datatype', u'dur', u'end', u'externalResourcesRequired', u'fill', u'focusHighlight', u'focusable', u'height', u'id', u'initialVisibility', u'max', u'min', u'nav-down', u'nav-down-left', u'nav-down-right', u'nav-left', u'nav-next', u'nav-prev', u'nav-right', u'nav-up', u'nav-up-left', u'nav-up-right', u'overlay', u'preserveAspectRatio', u'property', u'rel', u'repeatCount', u'repeatDur', u'requiredExtensions', u'requiredFeatures', u'requiredFonts', u'requiredFormats', u'resource', u'restart', u'rev', u'role', u'syncBehavior', u'syncMaster', u'syncTolerance', u'systemLanguage', u'transform', u'transformBehavior', u'type', u'typeof', u'width', u'x', u'xlink:actuate', u'xlink:arcrole', u'xlink:href', u'xlink:role', u'xlink:show', u'xlink:title', u'xlink:type', u'xml:base', u'xml:id', u'xml:lang', u'xml:space', u'y'],
    properties=media_group_names,
    children=[u'animate', u'animateColor', u'animateMotion', u'animateTransform', u'desc', u'discard', u'handler', u'metadata', u'set', u'switch', u'title']),

}
